name: Auto Merge

on:
  pull_request_review:
    types:
      - submitted

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto Merge PR
        env:
          SECRET: ${{ secrets.MERGE }}
        run: |
          PR_URL=$(jq -r ".pull_request.url" "$GITHUB_EVENT_PATH")
          PR_NUMBER=$(jq -r ".pull_request.number" "$GITHUB_EVENT_PATH")
          echo "Pull Request URL: $PR_URL"
          echo "Pull Request Number: $PR_NUMBER"

          API_RESPONSE=$(curl -s -H "Authorization: Bearer $SECRET" "$PR_URL/reviews")
          echo "API Response: $API_RESPONSE"

          APPROVALS=$(echo "$API_RESPONSE" | jq '.[] | select(.state == "APPROVED") | .user.login' | wc -l)
          echo "Secret Value: $SECRET"
          
          if [ "$APPROVALS" -ge 1 ]; then
          curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $SECRET" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "$PR_URL/merge" \
          -d '{"merge_method": "merge"}' 
          fi
