name: Auto Merge

on:
  pull_request_review:
    types:
      - submitted

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto Merge PR
        run: |
          apt install jq
          PR_URL=$(jq -r ".pull_request.url" "$GITHUB_EVENT_PATH")
          PR_NUMBER=$(jq -r ".pull_request.number" "$GITHUB_EVENT_PATH")
          echo "Pull Request URL: $PR_URL"
          echo "Pull Request Number: $PR_NUMBER"  
          API_RESPONSE=$(curl -s -H "Authorization: ***" "$PR_URL/reviews")
          echo "API Response: $API_RESPONSE"

          APPROVALS=$(echo "$API_RESPONSE" | jq '.[] | select(.state == "APPROVED") | .user.login' | wc -l)


          if [ "$APPROVALS" -ge 1 ]; then
            curl -s -X PUT -H "Authorization: Bearer zzz" -d '{"merge_method": "merge"}' "$PR_URL/merge"
          fi
