name: Auto Merge

on:
  pull_request_review:
    types:
      - submitted

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto Merge PR
        run: |
          PR_URL=$(jq -r ".pull_request.url" "$GITHUB_EVENT_PATH")
          PR_NUMBER=$(jq -r ".pull_request.number" "$GITHUB_EVENT_PATH")
          echo "Pull Request URL: $PR_URL"
          echo "Pull Request Number: $PR_NUMBER"  
          APPROVALS=$(curl -s -H "Authorization: Bearer " "https://api.github.com/repos/${{github.repository_owner}}/${{github.repository.name}}/pulls/$PR_NUMBER/reviews" | jq '[.[] | select(.state == "APPROVED") | .user.login] | length')

          if [ "$APPROVALS" -ge 1 ]; then
            curl -s -X PUT -H "Authorization: Bearer ${{ secrets.AUTO_MERGE }}" -d '{"merge_method": "merge"}' "$PR_URL/merge"
          fi
